[package]
name = "gpuarray"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]
edition = "2018"

[dependencies.opencl]
git = "https://github.com/tedsta/rust-opencl"

[dependencies]
libc = "^0.1.8"
